# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_pb2 as ai__pb2


class WorkerPoolStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Work = channel.unary_unary(
                '/pb.WorkerPool/Work',
                request_serializer=ai__pb2.WorkerInfo.SerializeToString,
                response_deserializer=ai__pb2.WorkRequest.FromString,
                )
        self.CompleteWork = channel.unary_unary(
                '/pb.WorkerPool/CompleteWork',
                request_serializer=ai__pb2.WorkResponse.SerializeToString,
                response_deserializer=ai__pb2.WorkResponseAck.FromString,
                )


class WorkerPoolServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Work(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerPoolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Work': grpc.unary_unary_rpc_method_handler(
                    servicer.Work,
                    request_deserializer=ai__pb2.WorkerInfo.FromString,
                    response_serializer=ai__pb2.WorkRequest.SerializeToString,
            ),
            'CompleteWork': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteWork,
                    request_deserializer=ai__pb2.WorkResponse.FromString,
                    response_serializer=ai__pb2.WorkResponseAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.WorkerPool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerPool(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Work(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.WorkerPool/Work',
            ai__pb2.WorkerInfo.SerializeToString,
            ai__pb2.WorkRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.WorkerPool/CompleteWork',
            ai__pb2.WorkResponse.SerializeToString,
            ai__pb2.WorkResponseAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
